version: "3.9"
services:
    wastedetectionfrontend:
        build: .
        ports:
            - "5173:5173"
        depends_on:
            - wastedetectionbackend
    wastedetectionbackend:
        image: wastedetectionbackend
        ports:
            - "8000:8000"