version: "3.9"
services:
    wastedetectionfrontend:
        image: rbarile17/wastedetectionfrontend
        ports:
            - "5173:5173"
        depends_on:
            - wastedetectionbackend
    wastedetectionbackend:
        image: rbarile17/wastedetectionbackend
        ports:
            - "8000:8000"