version: "3.9"
services:
    wastedetectionfrontend:
        image: wastedetectionfrontend
        container_name: wastedetectionfrontend
        ports:
            - "5173:5173"
        depends_on:
            - wastedetectionbackend
    prometheus:
        image: prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        depends_on:
            - wastedetectionbackend
    wastedetectionbackend:
        container_name: wastedetectionbackend
        image: wastedetectionbackend
        ports:
            - "8000:8000"