version: "3.9"
services:
    wastedetectionfrontend:
        image: rbarile17/wastedetectionfrontend
        container_name: wastedetectionfrontend
        ports:
            - "5173:5173"
        depends_on:
            - wastedetectionbackend
    wastedetectiongrafana:
        image: grafana/grafana
        container_name: wastedetectiongrafana
        ports:
            - "3000:3000"
        depends_on:
            - wastedetectionprometheus
    wastedetectionprometheus:
        image: rbarile17/wastedetectionprometheus
        container_name: wastedetectionprometheus
        ports:
            - "9090:9090"
        depends_on:
            - wastedetectionbackend
    wastedetectionbackend:
        image: rbarile17/wastedetectionbackend
        container_name: wastedetectionbackend
        ports:
            - "8000:8000"